using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AzureBillingViewer.Services {
  public class AzureRegion {
    public string Id { get; set; }
    public string CurrencyCode { get; set; }
    public string Name { get; set; }
  }

  public class AzureRegionService {
    public static IEnumerable<AzureRegion> List() {
      return new List<AzureRegion> {
        new AzureRegion {Id="AF", CurrencyCode="USD", Name="Afghanistan"},
        new AzureRegion {Id="AL", CurrencyCode="USD", Name="Albania"},
        new AzureRegion {Id="DZ", CurrencyCode="USD", Name="Algeria"},
        new AzureRegion {Id="AO", CurrencyCode="USD", Name="Angola"},
        new AzureRegion {Id="AR", CurrencyCode="ARS", Name="Argentina"},
        new AzureRegion {Id="AM", CurrencyCode="USD", Name="Armenia"},
        new AzureRegion {Id="AU", CurrencyCode="AUD", Name="Australia"},
        new AzureRegion {Id="AT", CurrencyCode="EUR", Name="Austria"},
        new AzureRegion {Id="AZ", CurrencyCode="USD", Name="Azerbaidjan"},
        new AzureRegion {Id="BS", CurrencyCode="USD", Name="Bahamas"},
        new AzureRegion {Id="BH", CurrencyCode="USD", Name="Bahrain"},
        new AzureRegion {Id="BD", CurrencyCode="USD", Name="Bangladesh"},
        new AzureRegion {Id="BB", CurrencyCode="USD", Name="Barbados"},
        new AzureRegion {Id="BY", CurrencyCode="USD", Name="Belarus"},
        new AzureRegion {Id="BE", CurrencyCode="EUR", Name="Belgium"},
        new AzureRegion {Id="BZ", CurrencyCode="USD", Name="Belize"},
        new AzureRegion {Id="BM", CurrencyCode="USD", Name="Bermuda"},
        new AzureRegion {Id="BO", CurrencyCode="USD", Name="Bolivia"},
        new AzureRegion {Id="BA", CurrencyCode="USD", Name="Bosnia-Herzegovina"},
        new AzureRegion {Id="BW", CurrencyCode="USD", Name="Botswana"},
        new AzureRegion {Id="BR", CurrencyCode="BRL", Name="Brazil"},
        new AzureRegion {Id="BN", CurrencyCode="USD", Name="Brunei Darussalam"},
        new AzureRegion {Id="BG", CurrencyCode="EUR", Name="Bulgaria"},
        new AzureRegion {Id="CM", CurrencyCode="USD", Name="Cameroon"},
        new AzureRegion {Id="CA", CurrencyCode="CAD", Name="Canada"},
        new AzureRegion {Id="CV", CurrencyCode="USD", Name="Cape Verde"},
        new AzureRegion {Id="KY", CurrencyCode="USD", Name="Cayman Islands"},
        new AzureRegion {Id="CL", CurrencyCode="USD", Name="Chile"},
        new AzureRegion {Id="CO", CurrencyCode="USD", Name="Colombia"},
        new AzureRegion {Id="CR", CurrencyCode="USD", Name="Costa Rica"},
        new AzureRegion {Id="CI", CurrencyCode="USD", Name="Ivory Coast (Cote D'Ivoire)"},
        new AzureRegion {Id="HR", CurrencyCode="EUR", Name="Croatia"},
        new AzureRegion {Id="CW", CurrencyCode="USD", Name="Curacao"},
        new AzureRegion {Id="CY", CurrencyCode="EUR", Name="Cyprus"},
        new AzureRegion {Id="CZ", CurrencyCode="EUR", Name="Czech Republic"},
        new AzureRegion {Id="DK", CurrencyCode="DKK", Name="Denmark"},
        new AzureRegion {Id="DO", CurrencyCode="USD", Name="Dominican Republic"},
        new AzureRegion {Id="EC", CurrencyCode="USD", Name="Ecuador"},
        new AzureRegion {Id="EG", CurrencyCode="USD", Name="Egypt"},
        new AzureRegion {Id="SV", CurrencyCode="USD", Name="El Salvador"},
        new AzureRegion {Id="EE", CurrencyCode="EUR", Name="Estonia"},
        new AzureRegion {Id="ET", CurrencyCode="USD", Name="Ethiopia"},
        new AzureRegion {Id="FO", CurrencyCode="EUR", Name="Faroe Islands"},
        new AzureRegion {Id="FJ", CurrencyCode="USD", Name="Fiji"},
        new AzureRegion {Id="FI", CurrencyCode="EUR", Name="Finland"},
        new AzureRegion {Id="FR", CurrencyCode="EUR", Name="France"},
        new AzureRegion {Id="GE", CurrencyCode="USD", Name="Georgia"},
        new AzureRegion {Id="DE", CurrencyCode="EUR", Name="Germany"},
        new AzureRegion {Id="GH", CurrencyCode="USD", Name="Ghana"},
        new AzureRegion {Id="GR", CurrencyCode="EUR", Name="Greece"},
        new AzureRegion {Id="GT", CurrencyCode="USD", Name="Guatemala"},
        new AzureRegion {Id="HN", CurrencyCode="USD", Name="Honduras"},
        new AzureRegion {Id="HK", CurrencyCode="HKD", Name="Hong Kong"},
        new AzureRegion {Id="HU", CurrencyCode="EUR", Name="Hungary"},
        new AzureRegion {Id="IS", CurrencyCode="EUR", Name="Iceland"},
        new AzureRegion {Id="IN", CurrencyCode="INR", Name="India"},
        new AzureRegion {Id="ID", CurrencyCode="IDR", Name="Indonesia"},
        new AzureRegion {Id="IQ", CurrencyCode="USD", Name="Iraq"},
        new AzureRegion {Id="IE", CurrencyCode="EUR", Name="Ireland"},
        new AzureRegion {Id="IL", CurrencyCode="USD", Name="Israel"},
        new AzureRegion {Id="IT", CurrencyCode="EUR", Name="Italy"},
        new AzureRegion {Id="JM", CurrencyCode="USD", Name="Jamaica"},
        new AzureRegion {Id="JP", CurrencyCode="JPY", Name="Japan"},
        new AzureRegion {Id="JO", CurrencyCode="USD", Name="Jordan"},
        new AzureRegion {Id="KZ", CurrencyCode="USD", Name="Kazakhstan"},
        new AzureRegion {Id="KE", CurrencyCode="USD", Name="Kenya"},
        new AzureRegion {Id="KR", CurrencyCode="KRW", Name="South Korea"},
        new AzureRegion {Id="KW", CurrencyCode="USD", Name="Kuwait"},
        new AzureRegion {Id="KG", CurrencyCode="USD", Name="Kyrgyzstan"},
        new AzureRegion {Id="LV", CurrencyCode="EUR", Name="Latvia"},
        new AzureRegion {Id="LB", CurrencyCode="USD", Name="Lebanon"},
        new AzureRegion {Id="LY", CurrencyCode="USD", Name="Libya"},
        new AzureRegion {Id="LI", CurrencyCode="CHF", Name="Liechtenstein"},
        new AzureRegion {Id="LT", CurrencyCode="EUR", Name="Lithuania"},
        new AzureRegion {Id="LU", CurrencyCode="EUR", Name="Luxembourg"},
        new AzureRegion {Id="MO", CurrencyCode="USD", Name="Macau"},
        new AzureRegion {Id="MK", CurrencyCode="USD", Name="Macedonia"},
        new AzureRegion {Id="MY", CurrencyCode="MYR", Name="Malaysia"},
        new AzureRegion {Id="MT", CurrencyCode="EUR", Name="Malta"},
        new AzureRegion {Id="MU", CurrencyCode="USD", Name="Mauritius"},
        new AzureRegion {Id="MX", CurrencyCode="MXN", Name="Mexico"},
        new AzureRegion {Id="MD", CurrencyCode="USD", Name="Moldavia"},
        new AzureRegion {Id="MC", CurrencyCode="EUR", Name="Monaco"},
        new AzureRegion {Id="MN", CurrencyCode="USD", Name="Mongolia"},
        new AzureRegion {Id="ME", CurrencyCode="USD", Name="Montenegro"},
        new AzureRegion {Id="MA", CurrencyCode="USD", Name="Morocco"},
        new AzureRegion {Id="NA", CurrencyCode="USD", Name="Namibia"},
        new AzureRegion {Id="NP", CurrencyCode="USD", Name="Nepal"},
        new AzureRegion {Id="NL", CurrencyCode="EUR", Name="Netherlands"},
        new AzureRegion {Id="NZ", CurrencyCode="NZD", Name="New Zealand"},
        new AzureRegion {Id="NI", CurrencyCode="USD", Name="Nicaragua"},
        new AzureRegion {Id="NG", CurrencyCode="USD", Name="Nigeria"},
        new AzureRegion {Id="NO", CurrencyCode="NOK", Name="Norway"},
        new AzureRegion {Id="OM", CurrencyCode="USD", Name="Oman"},
        new AzureRegion {Id="PK", CurrencyCode="USD", Name="Pakistan"},
        new AzureRegion {Id="PS", CurrencyCode="USD", Name="Palestinian Authority"},
        new AzureRegion {Id="PA", CurrencyCode="USD", Name="Panama"},
        new AzureRegion {Id="PY", CurrencyCode="USD", Name="Paraguay"},
        new AzureRegion {Id="PE", CurrencyCode="USD", Name="Peru"},
        new AzureRegion {Id="PH", CurrencyCode="USD", Name="Philippines"},
        new AzureRegion {Id="PL", CurrencyCode="EUR", Name="Poland"},
        new AzureRegion {Id="PT", CurrencyCode="EUR", Name="Portugal"},
        new AzureRegion {Id="PR", CurrencyCode="USD", Name="Puerto Rico"},
        new AzureRegion {Id="QA", CurrencyCode="USD", Name="Qatar"},
        new AzureRegion {Id="RO", CurrencyCode="EUR", Name="Romania"},
        new AzureRegion {Id="RU", CurrencyCode="RUB", Name="Russian Federation"},
        new AzureRegion {Id="RW", CurrencyCode="USD", Name="Rwanda"},
        new AzureRegion {Id="KN", CurrencyCode="USD", Name="Saint Kitts & Nevis Anguilla"},
        new AzureRegion {Id="SA", CurrencyCode="SAR", Name="Saudi Arabia"},
        new AzureRegion {Id="SN", CurrencyCode="USD", Name="Senegal"},
        new AzureRegion {Id="RS", CurrencyCode="USD", Name="Serbia"},
        new AzureRegion {Id="SG", CurrencyCode="USD", Name="Singapore"},
        new AzureRegion {Id="SK", CurrencyCode="EUR", Name="Slovak Republic"},
        new AzureRegion {Id="SI", CurrencyCode="EUR", Name="Slovenia"},
        new AzureRegion {Id="ZA", CurrencyCode="ZAR", Name="South Africa"},
        new AzureRegion {Id="ES", CurrencyCode="EUR", Name="Spain"},
        new AzureRegion {Id="LK", CurrencyCode="USD", Name="Sri Lanka"},
        new AzureRegion {Id="SE", CurrencyCode="SEK", Name="Sweden"},
        new AzureRegion {Id="CH", CurrencyCode="CHF", Name="Switzerland"},
        new AzureRegion {Id="TW", CurrencyCode="TWD", Name="Taiwan"},
        new AzureRegion {Id="TJ", CurrencyCode="USD", Name="Tadjikistan"},
        new AzureRegion {Id="TZ", CurrencyCode="USD", Name="Tanzania"},
        new AzureRegion {Id="TH", CurrencyCode="USD", Name="Thailand"},
        new AzureRegion {Id="TT", CurrencyCode="USD", Name="Trinidad and Tobago"},
        new AzureRegion {Id="TN", CurrencyCode="USD", Name="Tunisia"},
        new AzureRegion {Id="TR", CurrencyCode="TRY", Name="Turkey"},
        new AzureRegion {Id="TM", CurrencyCode="USD", Name="Turkmenistan"},
        new AzureRegion {Id="UG", CurrencyCode="USD", Name="Uganda"},
        new AzureRegion {Id="UA", CurrencyCode="USD", Name="Ukraine"},
        new AzureRegion {Id="AE", CurrencyCode="USD", Name="United Arab Emirates"},
        new AzureRegion {Id="UK", CurrencyCode="GBP", Name="United Kingdom"},
        new AzureRegion {Id="US", CurrencyCode="USD", Name="United States"},
        new AzureRegion {Id="UY", CurrencyCode="USD", Name="Uruguay"},
        new AzureRegion {Id="UZ", CurrencyCode="USD", Name="Uzbekistan"},
        new AzureRegion {Id="VE", CurrencyCode="USD", Name="Venezuela"},
        new AzureRegion {Id="VN", CurrencyCode="USD", Name="Vietnam"},
        new AzureRegion {Id="VI", CurrencyCode="USD", Name="Virgin Islands (USA)"},
        new AzureRegion {Id="YE", CurrencyCode="USD", Name="Yemen"},
        new AzureRegion {Id="ZM", CurrencyCode="USD", Name="Zambia"},
        new AzureRegion {Id="ZW", CurrencyCode="USD", Name="Zimbabwe"}
      };
    }
  }
}